<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE trees [
<!ELEMENT trees (tree+)>
<!ELEMENT tree (Name,Kingdom,Subkingdom?,Division,Class,Subclass?,Order,Family,Subfamily?,Tribe?,Subtribe?,Genus,Species*,Zoological_name,Found_in,Other_names,Description,Other_species*,Location,Cultivation_methods,Medicinal_uses*,Other_uses,Cultural_importance*)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Kingdom (#PCDATA)>
<!ELEMENT Subkingdom (#PCDATA)>
<!ELEMENT Division (#PCDATA)>
<!ELEMENT Class (#PCDATA)>
<!ELEMENT Subclass (#PCDATA)>
<!ELEMENT Order (#PCDATA)>
<!ELEMENT Family (#PCDATA)>
<!ELEMENT Subfamily (#PCDATA)>
<!ELEMENT Tribe (#PCDATA)>
<!ELEMENT Subtribe (#PCDATA)>
<!ELEMENT Genus (#PCDATA)>
<!ELEMENT Species (#PCDATA)>
<!ELEMENT Zoological_name (#PCDATA)>
<!ELEMENT Found_in (#PCDATA)>
<!ELEMENT Other_names (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Other_species (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT Cultivation_methods (#PCDATA)>
<!ELEMENT Medicinal_uses (#PCDATA)>
<!ELEMENT Other_uses (#PCDATA)>
<!ELEMENT Cultural_importance (#PCDATA)>
]>
<trees>
	<tree>
		<Name>BanyanTree</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta</Division>
		<Class>Magnoliopsida</Class>
		<Order>Urticales</Order>
		<Family>Moraceae</Family>
		<Genus>Ficus</Genus>
		<Zoological_name>Ficus Benghalensis </Zoological_name>
		<Found_in>Ranthambore National Park and Corbett National Park </Found_in>
		<Other_names>Bargad, Bor, Ber, Ala and Pedda mari, Nayagrodha, Ala mara, Bar, Vad, Vatnam, Bahupada, Peddamarri, Al are the other names used for the Banyan tree. Indians call it a wish fulfilling tree</Other_names>
		<Description>Banyan tree is a huge tree with very extensive branches. It is said that at one time more than 10, 000 people can sit under its shade at one time. It is a evergreen tree. It branches spread out and send trunk like roots to the ground in order to support itself. It grows to a height of more than Banyan Tree21 meters and lives for many years. The leaves are 10 -20 cm long and has many aerial roots. The leaves are broad, oval and glossy. White milky fluid oozes out of leaves, if broken. It can grow in to the gaint tree covering several hectares</Description>
		<Other_species>F. aurea, F. benghalensis, F. citrifolia, F. macrophylla, F. microcarpa, F.pertusa, F. rubiginosa are the other related species of the Banyan tree</Other_species>
		<Location>Found in almost all the parts of India, Banyan tree is the National tree of India. It is grown throughout the sub- Himalayan region and in the deciduous forests. One can Banyan Tree in the Botanical Garden of Calcutta. They are widely grown in the Ranthambore National Park and Corbett National Park in India</Location>
		<Cultivation_methods>Banyan tree is easily propagated by root tip cuttings or the eye cuttings. Cut apiece of the stem about half a inch below and above the leaf. Insert the stem piece and a little of the leaf stalk into the rooting medium. To reduce evaporation from the leaf surface, you can roll the leaf and secure with a rubber band. In a couple weeks roots and a new shoot will start developing. It can grow in any type of soil</Cultivation_methods>
		<Medicinal_uses>The Banyan tree also has several medicinal properties. Its leaf, bark, seeds and fig are used for the variety of disorders like diarrhea, polyuria, dental, diabetes and urine disorders. The wood of the Banyan tree is used in making door panels, boxes and the other items. Its bark is used for making paper and ropes. The milky latex that comes from its leaves and stems is used in many Ayurvedic medicines</Medicinal_uses>
		<Other_uses>In India its edible leaves are used as the plates. It is planted for the soil conservation. Wood is used for well curbs, door panels, boxes, furniture etc. It is suitable for paper pulp. The wood of the aerial roots is stronger and is used for the tent poles and cart yokes</Other_uses>
		<Cultural_importance>Banyan tree is respected and is considered as sacred by the people in India. In the sacred Hindu Book 'Bhagwad Gita' Lord Krishna has sung praises on the Banyan tree. People in India grow Banyan tree closer to the Peepal tree. As Banyan tree is considered as the male plant closely related to the Peepal tree. It symbolize Trimurti with Vishnu as the barl, Shiva as the branches and Brahma as the roots. Indians considered Banyan tree as 'Kalpa Vriksha' the tree that fulfill all your wishes.The mighty Banyan Tree is considered as immortal and has always been the focal point for the village communities in India. It is probably the biggest and friendliest of all trees. Banyan tree is the tree of knowledge and tree of life</Cultural_importance>
	</tree>	
	<tree>
		<Name>Tulsi Plant</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta </Division>
		<Class>Magnoliopsida</Class>
		<Order>Lamiales</Order>
		<Family>Lamiaceae</Family>
		<Genus>Ocimum</Genus>
		<Species>O. tenuiflorum</Species>
		<Zoological_name>Ocimum Sanctum</Zoological_name>
		<Found_in>Gir National Park and Sasangir National Park</Found_in>
		<Other_names>It is known as Holy Basil in English and Tulasi in Sanskrit. Other names used for the Tulsi are Manjari, Krishna Tulsi, Trittavu, Tulshi and Thulsi</Other_names>	
		<Description>Tulsi is a heavy branched having hair all over. It attains the height of about 75 – 90 cm. It has round oval shaped leaves which are up to 5 cm long. The leaves are 2- 4 cm in length. Its seeds are flat. Its flowers are purple – creamish in colour. The Tulsi with the green leaves is called the Shri Tulsi and one with the reddish leaves is called the Krishna Tulsi. Its seeds are yellow to reddish in colour. Leaves of Tulsi contains very essential oil</Description>
		<Other_species>Ocimum canum (Ram tulsi or Kali Tulsi), Ocimum basilicum, Ocimum Kilmand, Ocimum scharicum are the other related species of the Tulsi (Ocimum Sanctum)</Other_species>
		<Location>Tulsi is widely grown in the Gir Wildlife Sanctuary and Sasangir National Park in India. Tulsi grows wild in tropics and warm regions</Location>
		<Cultivation_methods>Tulsi seeds germinate easily. The seeds are mainly sown in the spring season. They are watered from time to time and germinated in one to two weeks. Tulsi prefers rich soil for its growth. It requires full sunlight. It is mainly grown in the temperate climate</Cultivation_methods>
		<Medicinal_uses>Tulsi has got the great medicinal value. Tulsi is taken as the herbal tea. The oil extracted from the Karpoora Tulsi is mostly used in the herbal toiletry. Its oil is also used against the insects and bacteria. The Rama Tulsi is the effective remedy for the Severe acute Respiratory Syndrome. Juice of its leaves gives relief in cold, fever, bronchitis and cough. Tulsi oil is also used as the ear drop. Tulsi helps in curing malaria. It si very effective against indigestion, headache, hysteria, insomnia and cholera. The fresh leaves of Tulsi are taken by the million of people everyday. For over the centuries Tulsi (the queen of herbs) has been known for its remarkable healing properties</Medicinal_uses>
		<Other_uses>Many people wears the Tulsi beads, which is said to have certain physical and medicinal properties. Its wood is considered as more powerful than any other gem that helps in protecting one from the negative influences. One can also buy several handicraft jewellery items made of Tulsi wood</Other_uses>
		<Cultural_importance>Tulsi is the sacred plant dearer to the Lord Vishnu. Tulsi symbolises purity. It is considered as the holy plant in the Indian Subcontinent. Tulsi got its name from Tulasi Devi, who was one of Lord Krishna's eternal consorts. In India people grow Tulsi as the religious plant and worship it. Its leaves are used in temples for the worship purposes and also on the several occasions such as marriage. A Hindu house is considered incomplete without the Tulsi plant in the courtyard. Tulsi is belived to promote longevity and life long happiness. Hindus perform special Tulsi puja in the Kartik month which starts after Sharad Poornima. It is the time of the Tulsi vivah (marriage). On this day Tulsi is decorated and coloured as a bride.Even today people in India maintain a potted Tulsi plant. The womens water the plant, light up the diya near it and worships it daily. The stems, leaves, seeds and even the soil is considered as holy. According to the ancient texts Tulsi is glorified as the one who helps in bringing people closer to the divine</Cultural_importance>
	</tree>
	<tree>
		<Name>Peepal Tree</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta </Division>
		<Class>Magnoliopsida </Class>
		<Order>Rosales</Order>
		<Family>Moraceae </Family>
		<Genus>Ficus</Genus>
		<Species>F. religiosa </Species>
		<Zoological_name>Ficus religiosa</Zoological_name>
		<Found_in>Ranthambore Wildlife Sanctuary </Found_in>
		<Other_names>Bo tree, Bodhi tree, Sacred tree, Beepul tree, Pipers, Pimpal, Jari, Arani,Ashvattha, Ragi, Bodhidruma, Shuchidruma, Pipalla, Ashvattha and the Buddha tree are the other names used for the Banyan tree.</Other_names>
		<Description>Peepal is a large, fast growing deciduous tree. It has a heart shaped leaves. It is a medium size tree and has a large crown with the wonderful wide spreading branches. It shed its leaves in the month of March and April. The fruits of the Peepal are hidden with the figs. The figs are ripen in peepal-treethe month of May. The figs which contain the flowers grow in pairs just below the leaves and look like the berries. Its bark is light gray and peels in patches. Its fruit is purple in colour. It is one of the longest living trees</Description>
		<Other_species>Artocarpus heterophyllus Lam, Artocarpus incissus L., Artocarpus nobilis Thw. Are some of the other species of the Peepal tree.</Other_species>
		<Location>Peepal tree is grown throughout India. It is mainly grown in State of Haryana, Bihar, Kerala and Madhya Pradesh. It is also found in the Ranthambore National Park in India. </Location>
		<Cultivation_methods>Peepal tree is easily propagated through the seeds or through the cuttings. It can grow in any type of soil. Young peepal needs proper nourishment. It requires full sunlight and proper watering.</Cultivation_methods>
		<Medicinal_uses>This tree of life has also got the medicinal value. The juice of its leaves extracted by holding them near the fire can be used as the ear drop. Its power bark has been used to heal the wounds for years. The bark of the tree is useful in inflammations and glandular swelling of the neck. Its root bark is useful for stomatitis, clean ulcers, and promotes granulations. Its roots are also good for gout. The roots are even chewed to prevent gum diseases. Its fruit is laxative which promotes digestion and checks vomiting. Its ripe fruits are good for the foul taste, thirst and heart diseases. The powered fruit is taken for Asthma. Its seeds have proved useful in urinary troubles. The leaves are used to treat constipation.</Medicinal_uses>
		<Other_uses>People in India collect the Peepal leaves, clean them, dry them and than paint them with the gold acrylic in order to preserve them for years. From the bark of the Peepal tree reddish dye is extracted. Its leaves are used to feed the camels and the elephants. When the leaves are dried they are used for the decoration purpose.</Other_uses>
		<Cultural_importance>Peepal tree has the great importance in India especially among the Buddhist who regard Peepal tree as the personification of Buddha. Lord Buddha attained enlightenment mediating under the Peepal tree. It is regarded as the sacred tree and the people uses its leaves for the religious purposes. According to the Buddha – 'He who worships the Peepal tree will receive the same reward as if he worshiped me in person'. The Peepal tree has its own symbolic meaning of Enlightenment and peace. People tie threads of white, red and yellow silk around it to pray for progeny and rewarding parenthood. Hindus in India holds the great spiritual regard for the Peepal Tree, they regard it as the tree beneath which Vishnu was born. </Cultural_importance>
	</tree>	
	<tree>
		<Name>Neem Tree</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta </Division>
		<Class>Magnoliopsida</Class>
		<Order>Sapindales</Order>
		<Family>Meliaceae</Family>
		<Genus>Azadirachta</Genus>
		<Species>A. indica</Species>
		<Zoological_name>Azadirachta indica </Zoological_name>
		<Found_in>Ranthambore National Park, Bandhavgarh national Park, Mrugavani Naional Park, Bannerghata National Park, Sariska Wildlife sanctuary and Guindy National Park.</Found_in>
		<Other_names>It is popularly known as the miracle tree. It is known as Nimba in India. The Sanskrit name of Neem is Arishtha meaning the reliever of the sickness. Margosa tree</Other_names>
		<Description>It is a tall evergreen tree with the small bright green leaves. It is up to 100 feet tall. It blossoms in spring with the small white flowers. It has a straight trunk. Its bark is hard rough and scaly, fissured even in small trees. The colour of the bark is brown grayish. The leaves are alternate and consists of several leaflets with serrated edges. Its flowers are small and white in colour. The loive like edible fruit is oval, round and thin skinned.</Description>
		<Other_species>A. juss, A. azedarac are the other related species of Neem tree. A. juss, A. azedarac are the other related species of Neem tree. A. juss, A. azedarac are the other related species of Neem tree.</Other_species>
		<Location>Neem tree is found throughout India. It is a popular village tree. Although it is also widely grown in Ranthambore National Park, Bandhavgarh national Park, Mrugavani Naional Park, Bannerghata National Park, Sariska Wildlife Sanctuary and Guindy National Park.</Location>
		<Cultivation_methods>Neem tree can easily be grown in the dry, stony, shallow and clayey soils. It needs very little water and plenty of sunlight. It grows slowly during the first year of planting. It can be propagated through the seeds and cuttings. Young neem tree can not tolerate excessive cold.</Cultivation_methods>
		<Medicinal_uses>The indigenous people of Nilgiris consume the dried and powered tubulers of the terrestrial orchids as an energizing tonic. Neem also holds medicinal value. Each part of neem is used in the medicines. It has been used in Ayurvedic medicines for more than 4000 years. Neem oil extracted from its seeds is used in medicines, pest control and cosmetics etc. Its leaves are used in the treat Chickenpox.. According to the Hindus, it is believed that the Goddess of the chickenpox, Sithala lives in the Neem tree. Neem tea is usually taken to reduce the headache and fever. Its flowers are used to cure intestinal problems. Neem bark acts as an analgesic and can cure high fever as of malaria. Even the skin diseases can be cured from the Neem leaves. Indians even believe that the Neem can even purify diseases.</Medicinal_uses>
		<Other_uses>People in India use its twigs to brush their teeth. Neem is considered as the useful tree in rehabilitating the waste land areas. Neem seed pulp is useful for methane gas production. It is also useful as carbohydrate which is rich base for other industrial fermentations. Neem bark contains tannins which are used in tanning and dyeing. In south India its wood is used to make the furniture. The bark of the yields the fiber that is woven into ropes. Neem cake is widely used in India as fertilizer for sugarcane, vegetable and other cash crops. Many countries have been consistently growing the Neem tree against the global warming. The worldwide Neem Foundation has helped in making the people aware about the importance of neem and its uses globally. </Other_uses>
		<Cultural_importance>One can find Neem in almost all the parts of India. It is said that planting Neem tree in the house is a ensured passage to heaven. Its leaves are stung on the main entrance to remain away from the evil spirits. Brides take bath in the water filled with the Neem leaves. Newly born babies are laid upon the Neem leaves to provide them with the protective aura. Neem gives out more oxygen than other trees. The neem tree is also connected with the Sun, in the story of Neembark 'The Sun in the Neem tree'. Neem is the wonder tree and finds mention in the number of ancient texts.</Cultural_importance>
	</tree>	
	<tree>
		<Name>Garden Asparagus</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta</Division>
		<Class>Liliopsida</Class>
		<Order>Asparagales</Order>
		<Family>Asparagaceae</Family>
		<Genus>Asparagus</Genus>
		<Zoological_name>Asparagus officinalis</Zoological_name>
		<Found_in>Kouchibouguas National Park, Narnala Wildlife Sanctuary and Sariska Tiger Reserve</Found_in>
		<Other_names>Shatwar, sootmooli, halyan, Satavari, Asparagus root, Wild Aspargus are the other names used for the Garden Asparagus. Satavari means who posses hundred husbands</Other_names>
		<Description>Garden Asparagus grows to a height of 3 feet. It is an herbaceous perennial and is well known for its edible young shoots. It has fleshy roots and fern-like feathery foliage. Its roots grows 3 feet down in the soil. Young shoots are green succulent and tender. It has smooth and green Garden Asaparagus stems which are 4-6 feet tall. It has green slender branches which appear more like the leaves than the branches. It produces male and female flowers on the separate plants. Flowers are greenish, bell shaped, which grows in the group of 1 to 3. Round bright red berries are produced on the female plants and each berries contains several black seeds</Description>
		<Other_species>Asparagus aethiopicus, Asparagus africanus, Asparagus declinatus, Asparagus falcatus, Asparagus flagellaris, Asparagus scandens, Asparagus umbellatus, Asparagus plumosus, Asparagus macowanni, Asparagus asparagoides. Garden Asparagus is known to have more than 250 species all over the world</Other_species>
		<Location>Garden Asparagus found throughout India especially in the Northern India. It is widely grown in the jungles at an altitude of 8,000 feet. It is mainly grown in the gardens. It can also be found in the Kouchibouguas National Park, Narnala Wildlife Sanctuary and Sariska Wildlife Sanctuary in India</Location>
		<Cultivation_methods>It is mostly propagated through seed, which are allowed to grow for a year. It is mostly planted in the spring season. The plant prefers acid, neutral, and alkaline soil. It grows in semi shade or no shade. The pant is placed in the trench which is 12 -18 inches wide and six inches deep. The roots are spread out uniformly, with the crown bud side up, in an upright, centered position, slightly higher than the roots. It requires water regularly especially when it is young. Young shoots come out in early spring. It flowers in August and the seeds are ripen from September to October</Cultivation_methods>
		<Medicinal_uses>The roots of the plants are prescribed for the diarrhea and dysentery. They are useful in the nervous disorders. dyspepsia, and tumors, scalding of urine, throat infections, tuberculosis, cough, bronchitis and general debility. It is used in the treatment of the rheumatism and edema due to heart failure. The fresh juice taken in small dose acts medicinally as the diuretic and laxative. It an excellent form of folic acid, which is used in blood cell formation and prevention of liver diseases. It is also a good source of potassium, which helps in muscle recovery and prevents cramping. It is rich in Vitamin C, Thiamin, B6 and fiber. It contains rutin, which strengthens capillary walls, and GSH, which is the cancer fighter</Medicinal_uses>
		<Other_uses>The delicate flavour of Asparagus make it favourite among the vegetable lovers. They are normally boiled or steamed. There are so many vegetable recipes made out the Garden Asparagus. Its young shoots are taken as the raw salad. It contains low calorie. It has no fat at all</Other_uses>
	</tree>
	<tree>
		<Name>Arjuna Tree</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta </Division>
		<Class>Magnoliopsida </Class>
		<Order>Myrtales </Order>
		<Family>Combretaceae </Family>
		<Genus>Terminalia </Genus>
		<Species>T. arjuna</Species>
		<Zoological_name>Terminalia arjuna</Zoological_name>
		<Found_in>Bandhavgarh National Park, Pench Tiger Reserve and Kanha National Park</Found_in>
		<Other_names>Arjuna, Koha, Kahu, Arjan, White Marudah, White Murdh, Arjuna Myrobalan, Orjun, Yerra maddi, Sadada, Sadaru and many more.</Other_names>
		<Description>Arjuna is the large size deciduous tree. The height of the Arjuna tree reaches upto 60 -85 feet. It is the evergreen tree with the yellow flowers and conical leaves. It has a smooth gray bark. Fruit is 2.5 -3.5 cm long, fibrous woody, glabrous with 5 hard wings, striated with numerous arjun-treecurved veins. It has a buttressed trunk and a vast spreading crown from which the branches drop downwards. Its leaves are dull green above and pale brown beneath. Arjuna flowers between March to June and fruits between September to November.</Description>
		<Other_species>Terminalia chebula, T. bellrica and T. ciliata are the other species of Arjun tree found in India.</Other_species>
		<Location>Terminalia Arjuna is common throughout India especially in the sub Himalayan tracts and Eastern India. They are widely grown in Bandhavgarh National Park, Pench Tiger Reserve and Kanha National Park in India. It is mainly grown on the banks of the rivers and streams</Location>
		<Cultivation_methods>Its fruit is dried in the sunlight and than stored up to 6 -12 months. Seeds are pretreated by soaking in the water for 48 hours before sowing in beds. 8 – 9 months seedlings are better to transplant in the field. </Cultivation_methods>
		<Medicinal_uses>The Bark of the Arjuna tree contains calcium salts, magnesium salts, and glucosides has been used in traditional Ayurvedic herbalism Juice of its leaf is used to cure dysentry and earache. Arjuna helps in maintaining the cholesterol level at the normal rate, as it contains the antioxidant properties similar to the Vitamin E. It strengths the heart muscles and maintains the heart functioning properly. It also improves functioning of cardiac muscle. Arjuna is used for the treatment of coronary artery disease, heart failure, edema, angina and hypercholesterolemia. Its bark power possesses diuretic, prostaglandin enhancing and coronary risk factor modulating properties. It is also considered as beneficial in the treatment of Asthma</Medicinal_uses>
		<Other_uses>Its wood is used in boat and house building as it is very hard. Its wood is also used in the making of the agricultural implements and weapons too. It is grown in the cities and towns for the purpose of shade</Other_uses>
		<Cultural_importance>Arjuna is one of the sacred tree of India. It has acquired the social and religious sanctity with the passage of time. It is said that Arjuna has been born of the two sons of Kubair after saint Narada cursed him. The leaves and flowers of this tree are offered to the Lord Vishnu and Lord Ganpati on the several religious occasions. It has been used in Ayurvedic formation since ancient times</Cultural_importance>
	</tree>	
	<tree>
		<Name>Aloe Vera</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Magnoliophyta</Division>
		<Class>Liliopsida</Class>
		<Order>Asparagales</Order>
		<Family>Asphodelaceae</Family>
		<Genus>Aloe</Genus>
		<Species>A .vera</Species>
		<Zoological_name>Aloe Vera</Zoological_name>
		<Found_in>Ranthambore Wildlife Sanctuary </Found_in>
		<Other_names>Cape aloe, Aloe curacao, Barbadoes aloe, Venezuela aloe, Indian alces, Ghirita, Lu hui, Star Cactus are the other names used for the Aloe Vera. It is also called miracle plant, Burn plant, medicine plant and first-aid-plant</Other_names>
		<Description>Aloe Vera grows to a height of 12 to 16 inches. It has a fibrous root system. It does not have stems. It has thick freshly leaves with sharp points, which are up to 18 inches long and 2 inches wide at the base. Its leaves are even long and triangular in shape. The tissue in the center of the aloe-veraAloe leaf contains a gel which yields the aloe gel. Its leaves are rich in water that is why it can survive for years. These leaves have spiky margins and are blotched creams. It is the member of the Lilly family. The roots of the pant are thick and fibrous. The fruit is the triangular capsule containing numerous seeds</Description>
		<Other_species>There are more than 200 species of Aloe Vera. Aloe Barbadensis Miller, Aloe Saponaria, Aloe Chinensis, Aloe Variegata, Aloe Forex, Aloe Lalifolia and Curacao Aloe are some of the known species of Aloe Vera.</Other_species>
		<Location>Aloe Vera is cultivated throughout India. It is commonly found in Mumbai, Gujrat and South India. It mainly grows in the tropical and sub tropical areas. It grows well on sandy and well drained soil. It is widely grown in the Ranthambore National Park in India</Location>
		<Cultivation_methods>Aloe Vera plant is propagated through the seed. It prefers a well drained sandy soil in sunny location. Aloe Vera needs the temperature of above 40 degrees. They should be potted in the spring season and watered carefully until established. It grows in the arid climate. They should be watered regularly in the summers. But over watering can kill the plant. It also grows in partial shade. It reaches the maturity inn four years when the leaves are harvested. </Cultivation_methods>
		<Medicinal_uses>Aloe Vera is the herbal plant, used to heal the burn marks. Aloe Vera cures the skin diseases. It can also be used to remove dandruff from the hair. Aloe Vera is taken internally for the stomach disorders. The leaves of Aloe Vera is used for the treatment of facial edema or swelling. Its fluid is beneficial in reducing the inflammation and pain. Aloe Vera is used in cosmetics and even in the food industry. Curacao aloe acts as laxative, which is used against constipation. The fresh juice of its leaf blades can be applied directly to the ulcers, burns, sunburns, and fungal infection. Organic Aloe Vera juice reduces acidity. It prevents from fungus, influenza virus, measles, and high fever. </Medicinal_uses>
		<Other_uses>Aloe Vera is a very popular potted plant. It is grown in houses for the decoration. The leaf sap is used to make a soothing and healing moisturizing cream, which is good for the dry skin. It is used in the making of anti wrinkle cream. It is even used in the preparation of shampoos.</Other_uses>
		<Cultural_importance>Aloe Vera has been mentioned several times in the sacred scriptures. It is believed to have been used for the preservation of the body of the Jesus Christ. It is called as the plant of immorality. It is also mentioned in the holy book of Bible. It has been used by the tribal people as a medicine for the century</Cultural_importance>
	</tree>	
	<tree>
		<Name>Amla Plant</Name>
		<Kingdom>Plantae</Kingdom>
		<Division>Flowering plant</Division>
		<Class>Magnoliopsida </Class>
		<Order>Malpighiales </Order>
		<Family>Phyllanthaceae </Family>
		<Tribe>Phyllantheae</Tribe>
		<Subtribe>Fluegginae</Subtribe>
		<Genus>Phyllanthus </Genus>
		<Species>P. emblica </Species>
		<Zoological_name>Phyllanthus emblica</Zoological_name>
		<Found_in>Gir Wildlife Sanctuary</Found_in>
		<Other_names>Indian gooseberry, Bhumi amla, Bhumyamalki, Amlaki, adiphala, dhatri, amalaka, amali, amalakamu, usirikai, Anola, Amlika, nellikai, malacca tree, nillika, nellikya, emblic are the other names used for the Amla</Other_names>
		<Description>Amla is the medium size deciduous plant. It grows to the height of 8 -18 meter. It has a crooked trunk and spreading branches. Its flower is yellow greenish in colour. The fruit is spherical pale yellow with six vertical furrows. The mature fruits are hard and do not fall for the gentle touch. amla-plantThe average weight of the fruit is 60 -70 g. It has a gray bark and reddish wood. Its leaves are feathery, linear oblong in shape and smell like lemon. Its wood is hard in texture. It wraps and splits when exposed in the Sun or in the excessive heat. </Description>
		<Location>It is planted through the deciduous of tropical India and on the hill slopes up to 2000 meter. It is commercially cultivated in the state of Uttar Pradesh in India. It is also grown in Tamil Nadu, Rajasthan and Madhya Pradesh also.</Location>
		<Cultivation_methods>Amla can grow in light as well as the heavy soils. It is grown under the tropical conditions. The young plants are protected from the hot winds as they dye easily. Amla is generally propagated through seeds. It requires proper sunlight. It is irrigated during the monsoon season. It starts bearing fruits in seven years from the day of planting.</Cultivation_methods>
		<Medicinal_uses>The fruit is the richest source of Vitamin C and is a diuretic, aperient, Laxative and hair dye. It cures insomnia and is healthy for hair. It is used as the cardio protective, useful in hemorrhage, menprrhagia, leucorrhoea and discharge of blood from uterus. Amla power and oil are used traditionally in Ayurvedic applications for the treatment of scalp. Amla power improves immunity and gives physical strength. It improves complexion and removes wrinkles. Amla is also used to treat constipation and is used as a cooling agent to reduce the effects of sun strokes and sun burns.</Medicinal_uses>
		<Other_uses>It is the main ingredient used in the shampoo. Amla oil is used all the world. Amla is used in sauces, candy, dried chips, pickle, jellies and powder. It is even used in the dyeing industry. It extract is popularly used in the ink. Amla wood is commonly used in firework.</Other_uses>